add_executable(coter_math_rand_test rand_test.cpp)
add_test(NAME coter_math_rand_test COMMAND coter_math_rand_test)
target_link_libraries(coter_math_rand_test PRIVATE coter_compile_dependency coter::coter coter::testing_main)

add_executable(coter_math_bit_cast_test bit_cast_test.cpp)
add_test(NAME coter_math_bit_cast_test COMMAND coter_math_bit_cast_test)
target_link_libraries(coter_math_bit_cast_test PRIVATE coter_compile_dependency coter::coter coter::testing_main)

add_executable(coter_math_bit_test bit_test.cpp)
add_test(NAME coter_math_bit_test COMMAND coter_math_bit_test)
target_link_libraries(coter_math_bit_test PRIVATE coter_compile_dependency coter::coter coter::testing_main)
