name: Build
run-name: ${{ gitea.actor }} is building the project 🚀

on:
  push:
    branches:
      - master
      - develop
    paths:
      - "include/**"
      - "src/**"
      - "example/**"
      - "test/**"
      - "cmake/**"
      - "CMakeLists.txt"
      - "Taskfile.yml"
  pull_request:
    branches:
      - master
      - develop
    paths:
      - "include/**"
      - "src/**"
      - "example/**"
      - "test/**"
      - "cmake/**"
      - "CMakeLists.txt"
      - "Taskfile.yml"
  workflow_dispatch:

env:
  COTER_BUILD_EXAMPLE: "ON"
  COTER_BUILD_TEST: "ON"
  COTER_BUILD_SHARED: "OFF"

jobs:
  build:
    runs-on: ubuntu-5110
    container:
      image: local/ubuntu-5110:202510
      options: --network host
    steps:
      - name: Check out repository code
        uses: https://gitea.com/actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure Git for private repositories
        run: |
          git config --global http.http://192.168.1.47:3000.extraheader "Authorization: token ${{ secrets.READONLY_TOKEN }}"
      - name: Configure project
        run: task config
      - name: Run tests
        run: task test
