
# 设置项目名称
set(PROJECT_NAME coter)

# 设置版本号
set(BUILD_VERSION_MAJOR 0)
set(BUILD_VERSION_MINOR 1)
set(BUILD_VERSION_PATCH 1)
set(BUILD_VERSION_TWEAK 0)
set(BUILD_VERSION ${BUILD_VERSION_MAJOR}.${BUILD_VERSION_MINOR}.${BUILD_VERSION_PATCH}.${BUILD_VERSION_TWEAK})
