
# see configure
# Checks for header files
project_check_header("stdbool.h")
project_check_header("stdint.h")
project_check_header("stdatomic.h")
project_check_header("sys/types.h")
project_check_header("sys/stat.h")
project_check_header("sys/time.h")
project_check_header("fcntl.h")
project_check_header("pthread.h")
project_check_header("endian.h")
project_check_header("sys/endian.h")

project_check_function("gettid" "unistd.h")
project_check_function("strlcpy" "string.h")
project_check_function("strlcat" "string.h")
project_check_function("memrchr" "string.h")
project_check_function("clock_gettime" "time.h")
project_check_function("gettimeofday" "sys/time.h")
project_check_function("sem_timedwait" "semaphore.h")
project_check_function("pipe" "unistd.h")
project_check_function("socketpair" "sys/socket.h")
project_check_function("eventfd" "sys/eventfd.h")
project_check_function("setproctitle" "unistd.h")
project_check_function("pthread_spin_lock" "pthread.h")
project_check_function("pthread_mutex_timedlock" "pthread.h")

project_check_struct("struct timespec" "tv_sec" "time.h")
project_check_library_function("rt" "clock_gettime" "")

set(COTER_LIBS ${PTHREADS_LIBS})
if(WIN32)
    set(COTER_LIBS ${COTER_LIBS} secur32 crypt32 winmm iphlpapi ws2_32)
    set(COTER_LIBS ${COTER_LIBS} dbghelp)
elseif(UNIX)
    set(COTER_LIBS ${COTER_LIBS} pthread m dl)
    if(CMAKE_COMPILER_IS_GNUCC)
        set(COTER_LIBS ${COTER_LIBS} rt)
    endif()
endif()
